version: 2
registries:
  custom-nuget:
    type: nuget-feed
    url: "https://nuget.pkg.github.com/LegitSecurity/index.json"
    username: "eliran@legitsecurity.com"
    password: "${{secrets.TOKEN_PAT_ELIRAN}}"
  public-nuget:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json

updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - custom-nuget
      - public-nuget #rfdsgfdsgdfsds
#    allow:
#      - dependency-name: "Legit.Common.*"
#updates:
#  - package-ecosystem: "nuget"
#    directory: "/"
#    schedule:
#      interval: "daily"
#    registries:
#      - github
#    labels:
#      - "dependencies"
#      - "nuget"
#    allow:
#      - dependency-name: "Legit.Common.*"
#    ignore:
#      - dependency-name: "Legit.Common.*"
#        versions: [ "*.*.*-g" ] #r

